###
# Log Download manager service
###
kind: Service
apiVersion: v1
metadata:
  name: log-download-manager
  labels:
    cluster: management
    component: log-download-manager
  namespace: __NPH_NAMESPACE
spec:
  selector:
    cluster: management
    component: log-download-manager
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8940
    targetPort: 8940
